global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'claimshield-backend'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal allows docker container to access host address localhost:8000
      - targets: ['host.docker.internal:8000']
